version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: github.com/aws/aws-sdk-go-v2
    versions:
    - 0.31.0
    - 1.2.1
    - 1.3.0
    - 1.3.1
    - 1.3.2
    - 1.3.3
  - dependency-name: github.com/aws/aws-sdk-go-v2/config
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: github.com/aws/aws-sdk-go-v2/credentials
    versions:
    - 1.1.2
    - 1.1.3
    - 1.1.4
    - 1.1.5
  - dependency-name: github.com/aws/aws-sdk-go-v2/service/mediaconvert
    versions:
    - 1.1.2
    - 1.2.0
    - 1.2.1
  - dependency-name: github.com/google/gops
    versions:
    - 0.3.15
    - 0.3.16
    - 0.3.17
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
  - dependency-name: github.com/fsouza/ctxlogger
    versions:
    - 1.5.10
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.3
    - 3.13.4
  - dependency-name: golang
    versions:
    - 1.15.7.pre.alpine
    - 1.15.8.pre.alpine
    - 1.16.1.pre.alpine
    - 1.16.2.pre.alpine
- package-ecosystem: docker
  directory: "/drone"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.3
    - 3.13.4
